# Generated by Django 3.2.25 on 2025-12-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, default='Undefined', help_text='Undefined', max_length=50),
        ),
    ]
